name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install client dependencies
        working-directory: ./client
        run: |
          npm install

      - name: Install server dependencies
        working-directory: ./server
        run: |
          npm install
